### ISSUE TITLE
Is pinning nbclient to < 0.8 necessary?

### ISSUE THREAD

**Issue by fperez** [executablebooks/jupyter-cache#109]
### Describe the bug

Currently, in [pyproj.toml](https://github.com/executablebooks/jupyter-cache/blob/main/pyproject.toml#LL31C17-L31C17) there is:

```
    "nbclient>=0.2,<0.8",
```

This means that all tools that depend on jupyter-cache (such as jupyter-book) are currently causing a downgrade of nbclient in all environments.

Is this pin truly necessary? If not, it would be great to remove the pin, and if it is, to identify clearly which problem is requiring it so we can help. I couldn't find anything explaining why that pin was there.

Thanks!

### Reproduce the bug

Install jupyter-cache or any pacakge that depends on it (e.g. jupyter-book).

**Comment by ckastner** [comment]
I'd like to package jupyter-cache for Debian, but since we're already on 0.8, this is a problem for us, too.

**Comment by agoose77** [comment]
I'm tracking this.

**Comment by fperez** [comment]
Thx @agoose77 for this! Little by little, the jbook/myst workflow is getting nicer and nicer, much appreciated!
