### ISSUE TITLE
RFE: update for `nbclient` 0.6.x

### ISSUE THREAD

**Issue by kloczek** [executablebooks/jupyter-cache#84]
### Context

https://github.com/executablebooks/jupyter-cache/blob/e72c2121b460c8558f9e6257b3b53353b9e7f35c/pyproject.toml#L27-L31

Any chance to update `jupyter-cache` for `nbclient` 0.6.x?

**Comment by benbovy** [comment]
Unfortunately this causes failing sphinx builds on RTD (e.g., https://readthedocs.org/projects/ipytone/builds/17209345/), as `nbclient` is inconsistently upgraded to the last version on RTD (see https://github.com/readthedocs/readthedocs.org/issues/8890).

**Comment by njooma** [comment]
Is this still blocked by failing builds on RTD? (The link above is dead). Would love to see this updated! Thanks

**Comment by bsipocz** [comment]
nbclient upper limit has been removed, I'm closing this issue now.
